name: CI

on:
  push:
  workflow_dispatch:

jobs:
  lint-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nodecg/nodecg
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          repository: nodecg/nodecg
          path: ./nodecg-temp

      - name: Copy ./nodecg-temp > ./nodecg
        run: cp -r ./nodecg-temp ./nodecg

      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: ./nodecg/bundles/swc-overlays

      - name: Create npm config file
        working-directory: ./nodecg/bundles/swc-overlays
        run: echo "//npm.greensock.com/:_authToken=$GSAP_AUTH" >> .npmrc
        shell: bash
        env:
          GSAP_AUTH: ${{ secrets.GSAP_AUTH }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: ./nodecg/bundles/swc-overlays/package-lock.json

      - name: Update NPM
        run: npm install -g npm@7.19.1

      - name: Install NPM dependencies
        working-directory: ./nodecg/bundles/swc-overlays
        run: npm ci

      - name: Run ESLint on source
        working-directory: ./nodecg/bundles/swc-overlays
        run: npm run lint

      - name: Set up GitHub for SSH access
        if: github.ref == 'refs/heads/master'
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets['GH_SSH'] }}

      - name: Set git config
        if: github.ref == 'refs/heads/master'
        working-directory: ./nodecg/bundles/swc-overlays
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Build
        if: github.ref == 'refs/heads/master'
        working-directory: ./nodecg/bundles/swc-overlays
        run: |
          npm run clean
          npm run build

      - name: Clear source files
        if: github.ref == 'refs/heads/master'
        working-directory: ./nodecg/bundles/swc-overlays
        run: | 
          rm -rf ./src
          git add src

      - name: Commit built files
        if: github.ref == 'refs/heads/master'
        id: commit
        continue-on-error: true
        working-directory: ./nodecg/bundles/swc-overlays
        run: |
          git checkout -B build
          git add -f graphics
          git commit -m "Build result from master branch" -a

      - name: Push built files to "build" branch
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets['GITHUB_TOKEN'] }}
          branch: build
          directory: ./nodecg/bundles/swc-overlays
